### ISSUE TITLE
Bank Branch Future State - Video player displays black background before exit

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#10]
Build: 1.0.1
Floor plan: Banking Branch - Future State
Hotspot: BC-40 (video)

Video finishes and goes to black background before player window exits screen. Typical behavior is to keep white background in player as player window exits right.

**Comment by nathansizemore** [comment]
Last few video frames are black.
An updated video with ending white frames will solve this.
