### ISSUE TITLE
Retail Store-Current: RC-22 hotspot has inactive center

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#17]
Build: 1.0.1
Floor plan: Retail Store-Current State
Hotspot: RC-22

Hotpost is can only be activated by touching pulsing circle. Cannot be triggered by touching human figure inside circle (center of hotspot is dead).

**Comment by nathansizemore** [comment]
Duplicate #1

**Comment by jon-powell** [comment]
Verified
