### ISSUE TITLE
Retail Store - Future State - RC-67 video flashes black at end before exit

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#23]
Build: 1.0.1
Floor plan: Retail Store - Future State
Hotspot: RC-57 (Lexmark Branding Statement video w/Lexmark icon on floor plan)

Video finishes and leaves black background before player window exits screen. Typical behavior is to go to white background in player before player window exits.

**Comment by nathansizemore** [comment]
Duplicate #10
