### ISSUE TITLE
Retail Store-Future: RC-55, jump in animation at beginning

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#24]
Build: 1.0.1
Floor plan: Retail Store - Future State
Hotspot: RC-55 (animation)

Check for quick jump into a zoomed in view (just a few frames) and then back out to a zoomed out view when animation starts. Happens consistently.

–suspected testing platform, but does not happen with animations in other floor plans.

**Comment by nathansizemore** [comment]
Duplicate #19

**Comment by jon-powell** [comment]
Verified

**Comment by julius-jackson** [comment]
Resolved
