### ISSUE TITLE
Retail HQ-Future: RC-66, Dead hotspot initially, somewhat functional after RC-65 touched

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#28]
Build: 1.0.1
Floor plan: Retail HQ - Future State
Hotspot: RC-66

Sequence:
*Touched as the next to last item in entire floor plan to be triggered (only RC-67 is green and untouched)
*Hotspot is dead. Multiple touches; no result. Stays green.
*Then clicked on RC-65 (gray) and it worked as expected
*Tried RC-66 again and it worked on first touch.
*RC-66 turns gray with an active, working ring, but inactive center

**Comment by nathansizemore** [comment]
Can not replicate.  Enlarged the collider for a safety measure.

**Comment by jon-powell** [comment]
Verified.

**Comment by julius-jackson** [comment]
Resolved
