### ISSUE TITLE
Retail HQ - Future State - RC-67 video flashes black at end before exit

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#29]
Build: 1.0.1
Floor plan: Retail Store - Future State
Hotspot: RC-67 (video)

Video finishes and leaves black background before player window exits screen. Typical behavior is to go to white background in player and maintain white as player window exits.

**Comment by jon-powell** [comment]
Same issue as issue #23. Closing duplicate
