### ISSUE TITLE
Manufacturing - Factory - Current - MC-18 Animation does not play

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#32]
Build: 1.0.2
Floor Plan - Manufacturing, Factory, Current State
Hotspot: MC-18 (animation)
PRIORITY = HIGH, lost functionality

Animation does not play when hotspot is touched, just goes from white to gray. Subsequent attempts when hotspot is gray do not trigger animation. Rebooted application. Behavior is consistently repeatable.

**PLEASE CONFIRM BUG ASAP. VERSION 1.0.2 IS SCHEDULED FOR INSTALL ON 6/28. VERSION 1.0.1 DID NOT HAVE THIS BUG. I CANNOT INSTALL NEW BUILDS THAT INTRODUCE NEW BUGS.**

**Comment by jon-powell** [comment]
Bug confirmed. Will look into ASAP.

**Comment by jon-powell** [comment]
Fix Verified
