### ISSUE TITLE
 Retail HQ, Current State - Animation RC-13 is dead

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#33]
Build: 1.0.2
Floor Plan - Retail HQ, Current State
Hotspot: RC-13 (animation)
PRIORITY = HIGH

Animation does not play when hotspot is touched, hotspot stays white.

**Comment by jon-powell** [comment]
Not able to replicate bug. Hotspot is functioning properly here on test PC however we will take a look and advise.

**Comment by John-McDaniel** [comment]
We're talking about the extreme lower left corner of Retail HQ-Current State, right? Please see the video emailed to Jon.

**Comment by jon-powell** [comment]
Fix Verified
