### ISSUE TITLE
Manufacturing HQ - MC-68 volume does not match other clips: too loud

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#47]
Build: 1.0.6
Floor Plan: Manufacturing HQ-Future

Please match volume level of MC-68 (uses female VO provided) to the volume level of the animations that use the same VO files.

Provide finished .OGV file separately for manual placement into the existing XML file onsite.

**Comment by nathansizemore** [comment]
Completed. Will provide download link.
