### ISSUE TITLE
Manufacturing-Factory-Current-State - Text correction

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#5]
Build: 1.0.1
Floor plan: Manufacturing-Factory-Current-State
Matrix ID: MC-21

Replace <dash> in "floors-especially" with <comma> and <space> to read:

Did You Know?
Paper is still the #1 communication tool on many factory production floors, especially for weekly safety reports!

**Comment by nathansizemore** [comment]
Instructions state replace with `and` but your example shows a comma break.  Which one?
@John-McDaniel

**Comment by John-McDaniel** [comment]
weird. I thought I wrote to replace the hyphen with a comma.

It's correct with the comma, as in:

Did You Know?
Paper is still the #1 communication tool on many factory production floors, especially for weekly safety reports!

**Comment by nathansizemore** [comment]
Fixed in e29a6b4

**Comment by julius-jackson** [comment]
Resolved
