### ISSUE TITLE
Manufacturing-Distribution-Current-State - Text correction

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#6]
Build: 1.0.1
Floor plan: Manufacturing-Distribution-Current-State
Matrix ID: MC-11

Remove spurious "in" between "year" and "supporting" in popup text.

Should read:

Supply chain logistics providers can receive MILLIONS of paper documents each year supporting their shipments.

**Comment by jon-powell** [comment]
Verified

**Comment by julius-jackson** [comment]
MILLIONS NOT Capitalized

**Comment by julius-jackson** [comment]
Resolved
