### ISSUE TITLE
Floor plan: Insurance HQ-Future - popup text correction

### ISSUE THREAD

**Issue by John-McDaniel** [real-art/chaos-to-order-issues#8]
Build: 1.0.1
Floor plan: Insurance HQ-Future-State
Matrix ID: IC-39

Body copy of popup is mangled. Should read:

With Lexmark's MPS solution, data analysis drives real process change, saving over $25 million in print costs.

**Comment by jon-powell** [comment]
Verified

**Comment by julius-jackson** [comment]
Currently shows video. Should be a graphic pop-up

**Comment by julius-jackson** [comment]
This issue exists IC-39 is showing a video instead of a graphic popup

**Comment by nathansizemore** [comment]
Updated original bug description, IC-39 is in future state.

**Comment by julius-jackson** [comment]
Resolved
